### ISSUE TITLE
YahooAPI weekly stats url possible change

### ISSUE THREAD

**Issue by austinbeauch** [uberfastman/yfpy#25]
Hi again @uberfastman, I think Yahoo might've pulled a quick one on you and changed the call for weekly stats. Just want go get your opinion, and if they did indeed make a change I'd be glad to work on it and send another pull request. 

I came across this in `get_player_stats_by_week`, specifically [this line](https://github.com/uberfastman/yfpy/blob/develop/yfpy/query.py#L2149). The week specification is given by 

`;type=week;week=" + str(chosen_week),`,

 however I was noticing that this wasn't returning any player stats. 

Looking at Yahoo's wall of "[documentation](https://developer.yahoo.com/fantasysports/guide/)" that I'm sure you're familiar with, I found their week was specified via 

> https://fantasysports.yahooapis.com/fantasy/v2/team//roster;week=10

Changing our friendly line 2149/2150 to

`;week=" + str(chosen_week),`

appeared to solve the problem. Not sure if this is something NHL specific.

Not anything urgent, don't rush to check it out. Thanks again for all your work!

**Comment by uberfastman** [comment]
@austinbeauch something to note here is that if you remove the `type=week` parameter, the call will no longer be providing stats for a given _week_, but will _instead_ provide player stats for the entire _season_. This is the case for _both_ NHL and NFL. 

However, if I recall correctly, Yahoo only actually lets you get player stats by week for NFL. Due to the continuous nature of NHL/MLB/NBA vs. the weekly nature of NFL, they don't delineate player stats by week. Instead you have to use the approach in `get_player_stats_by_date` in order to get a player's stats for a given date. If you want a whole week then you have to iterate through all the days of the time period you want. Mildly annoying since it requires more calls, but it's just how they do it. You can see this difference is _slightly_ alluded to in the documentation [here](https://developer.yahoo.com/fantasysports/guide/#id29). 

Anyway, thanks for your continued efforts to help me make improvements to yfpy, I always appreciate that, as well as you using it! 😃
