### ISSUE TITLE
get_league_transactions() returns single quote json property

### ISSUE THREAD

**Issue by Shafquat** [uberfastman/yfpy#4]
Hi,
When querying the get_league_transactions(), a json object returns a property in single quotes
![image](https://user-images.githubusercontent.com/1703503/67595299-4f29a480-f734-11e9-8ccc-1479f0b92c27.PNG)

This returns the following error when trying to convert the object into json using `json.loads(str(yahoo_query.get_league_transactions()))`

> returns an error of JSONDecodeError: Expecting property name enclosed in double quotes

**Comment by uberfastman** [comment]
Thanks for bringing this to my attention @Shafquat. I did a little digging, and it turns out this is not the only method that this is happening in... unfortunately, I got so wrapped up in adding baked-in JSON functionality that I didn't really consider what would happen if someone just sent the data straight to a JSON encoder themself.

I agree that this needs to be changed, but I think it might entail reconfiguring some of the more finicky parts of my Yahoo data parsing logic, so I'll need to set aside some time for that. 

In the meantime, you can avoid _any_ JSON issues by using the `yffpy.data` object, which lets you `save` and `load` data to/from JSON, and seems to avoid this error somehow. I've figured out _where_ this is happening, just not _why_ precisely, so I'm going to leave this ticket open until I have some sort of resolution. 

Thanks!

**Comment by uberfastman** [comment]
@Shafquat, commit dec92a2c99882f5edf5ae5c4f07fe0bff2fc6ccf adds a flag to the YFPY query class, which allows you to set `all_output_as_json` to `True`, enabling the direct return of a yfpy query as a JSON string. I decided to implement it this way so that if using yfpy within other python code, it still defaults to Python objects, but also gives you the option to get raw serializable JSON as well if you just want the returned data without doing anything else with it as Python objects. 

So if you upgrade to yfpy v3.1.1, you can add the flag as seen in the `__init__` of the `YahooFantasySportsQuery` class.
